### ISSUE TITLE
Correctly handle SLI inheritance across service, stage and projects as documented

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-sli-service#112]
In the doc - https://keptn.sh/docs/0.7.x/quality_gates/sli/#add-sli-configuration-to-a-service-stage-or-project - we explain that SLIs can be defined on any level, e.g: stage, service and project and that the sli-provider should "merge" / "inherit" SLI definitions

Seems the current dynatrace-sli-service implementation is not doing this. It looks at service, then stage and then project - BUT - it will take the first SLI.yaml it finds and then doesnt go "up the hierarchy" to also include the SLI definitions from higher level structures.

This was brought to our attention by one of our users who followed the doc but then highlighted by @christian-kreuzberger-dtx that this is actually not as implemented right now. Here is the problematic code: https://github.com/keptn-contrib/dynatrace-sli-service/blob/64f9502d8ed24db4b10c5207b064fa4ab1f0a375/pkg/common/common.go#L160-L164

**Comment by arthurpitman** [comment]
Closing this as it was fixed in #110
