### ISSUE TITLE
Create a Helm Chart for installing dynatrace-sli-service instead of Kubernetes deployment manifests 

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-sli-service#163]
In order to align the dynatrace-sli-service with the dynatrace-service, it should provide a Helm Chart for installation (see https://github.com/keptn-contrib/dynatrace-service/issues/261) 

This Helm Chart should have all Environment variables provided as values.

# Definition of Done

- [ ] Make sure that skaffold works with the provided Helm Chart (see solution: https://github.com/keptn/keptn/issues/3421)
- [ ] Helm Chart for dynatrace-sli-service with respective values provided
- [ ] README updated with usage examples
- [ ] When releasing a new version, the Helm Chart needs to be an asset of the release (automation?)
- [ ] Tutorials on tutorials.keptn.sh updated with new install instructions

**Comment by agrimmer** [comment]
Note, please don't delete the manifests in deploy folder! Please only mark them as deprecated.
