### ISSUE TITLE
Link Back to SLI Provider in Keptn's Bridge

### ISSUE THREAD

**Issue by leonvzGit** [keptn-contrib/dynatrace-sli-service#35]
Is it possible to provide a link back to your SLI provider in the Evaluation Events on Keptn's bridge?, eg the performance signature plugin provides a link back to Dynatrace's  Diagnostic tools--> Top Web requests for the evaluation period. 

I have found this to be a great context provider for testers and developers, it encourages them to log into Dynatrace directly from the results and get going with the diagnostics of the performance problem

**Comment by johannes-b** [comment]
Hi Leon, 
great idea and many thanks for the issue!
We already started a discussion around this idea in the following Keptn Enhancement Proposal: https://github.com/keptn/enhancement-proposals/pull/4. 

I will reference your issue at the discussion of the proposal.

**Comment by grabnerandi** [comment]
The Dynatrace-SLI Service now gives you the option to use a dashboard for SLI/SLO validation. If this option is chosen, the dynatrace-sli-service will add the link back to that dashboard with the correct timeframe to the SLI-done event as a label.
To make this integration even better the link should be clickable as right now you have to copy/paste the link from the cloud native event. An RFE for this "clickable label links" has already been created in the keptn/keptn project: https://github.com/keptn/keptn/issues/2061

**Comment by johannes-b** [comment]
With the new feature of having clickable links (see https://github.com/keptn/keptn/issues/2061) this issue can be closed.
