### ISSUE TITLE
Labels are being dropped between the get-sli and the get-sli.done keptn events

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-sli-service#37]
**Describe the bug**

Labels are being dropped between the get-sli and the get-sli.done keptn events.

**To Reproduce**

Add a label to a start evaluation event and then review the sli done event.

**Expected behavior**
The labels in the event are not dropped.

**Comment by christian-kreuzberger-dtx** [comment]
This is also already mentioned in https://github.com/keptn/keptn/issues/1151.

Anyway, we should switch the service to the latest go-utils and use the utility functions provided in there to process cloud-events. This takes care of sending labels.

**Comment by christian-kreuzberger-dtx** [comment]
@johannes-b this has been fixed in your PR, so we can close this issue, right?
