### ISSUE TITLE
Update this service to keptn/go-utils@v0.6.2 (and newer)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-sli-service#41]
I just tried udpating this services dependency of keptn/go-utils from v0.6.1 to v0.6.2, which unfortunately failed. 

Several things break in the code due to heavy refactoring of go-utils.

To reproduce:
* Clone the repo
* Execute `go get github.com/keptn/go-utils@v0.6.2`
* Run tests: `go test ./...`

**Comment by grabnerandi** [comment]
Working in it in branch slifromdashboard
