### ISSUE TITLE
Send back a get-sli.done with status failed when no dynatrace credentials could be retrieved

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-sli-service#49]
When sending a start-evaluation cloud-event via Keptn 0.6.2, the service does not respond at all if no dynatrace credentials are configured.

It should be easy enough to return a get-sli.done event with each SLO having a failed status, as no dynatrace credentials were set.

This would improve the user-experience in the case of forgetting to set the credentials.

This is currently handled in the `retrieveMetrics` function here: https://github.com/keptn-contrib/dynatrace-sli-service/blob/ca3138fb5272520103226e7d5b38fdccdd064223/cmd/main.go#L129-L133

**Comment by grabnerandi** [comment]
This was implemented in a way that every SLI metric value will return 0 with a status of failed and an error message indicating what the problem was, e.g: missing credentials.
