### ISSUE TITLE
Too strict check of endtime to be in the future

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-sli-service#55]
When the system that sends a start-evaluation event with an end timestamp of time.Now() is slightly ahead of the k8s cluster where Keptn runs then the Dynatrace SLI SErvice errors out with a "endtime is in the future". 
This happened to me when running through some of the quality gate tutorials that are using the keptn cli to send a start-evaluation event. Like this:
```
keptn send event start-evaluation --project=qgproject --stage=qualitystage --service=evalservice --timeframe=10m
```

As my laptop is about 1.5s ahead of the EKS cluster where Keptn runs I can never get this use case to work. As the SLI Service has a built-in 120s retry to Dynatrace anyway to avoid this situation I suggest to ease up that time restriction to e.g: 30s. This will solve this problem and will allow users to use the keptn CLI for kicking off qulaity gates even though their local clock might be off by a couple of seconds

**Comment by christian-kreuzberger-dtx** [comment]
Relevant part of code can be easily adapted:
```golang
	// ensure end time is not in the future
	if time.Now().Sub(endUnix).Seconds() < 0 {
		fmt.Printf("ERROR: Supplied end-time %v is in the future\n", endUnix)
		return 0, errors.New("end time must not be in the future")
	}

	// ensure start time is before end time
	if endUnix.Sub(startUnix).Seconds() < 0 {
		fmt.Printf("ERROR: Start time needs to be before end time\n")
		return 0, errors.New("start time needs to be before end time")
	}

```
