### ISSUE TITLE
Use k8s ServiceAccount with a restricted set of permissions instead of default

### ISSUE THREAD

**Issue by agrimmer** [keptn-contrib/dynatrace-sli-service#58]
Currently, the service uses the `default` Service Account with a set of high privileges inside the k8s clusters.

Use a dedicated service account with a minimum set of privileges as described in our contributing guidelines here https://github.com/keptn-sandbox/contributing/pull/2

**Definition of Done**:
- Service either uses the `keptn-default` Service Account which has no privileges at all or a new, dedicated Service Account with a minimal set of permissions

**Comment by christian-kreuzberger-dtx** [comment]
This service requires READ access to Dynatrace credentials, which are stored as Secrets in Kubernetes in the `keptn` namespace using the following naming schema:
* `dynatrace`
* `dynatrace-credentials`
* `dynatrace-credentials-${PROJECT}`
* Any other name specified in the `dynatrace.conf.yaml` file

So I conclude that this service needs read access to all secrets in the Keptn namespace. The same will be true for [dynatrace-service](https://github.com/keptn-contrib/dynatrace-service) - cross-referencing this issue.
