### ISSUE TITLE
add https_proxy/http_proxy env var support

### ISSUE THREAD

**Issue by luisr-escobar** [keptn-contrib/dynatrace-sli-service#74]
Container image is missing packages needed to allow alpine linux to connect outside the cluster using an http proxy.

Adding the following packages to the Dockerfile and rebuilding image fixed the problem.

`apk add curl netcat-openbsd`

**Comment by agrimmer** [comment]
We at least have to provide a flag for disabling the SSL verification.
Therefore, I propose to introduce an environment variable `HTTP_SSL_VERIFY`, which allows disabling the SSL verification.

**Comment by arthurpitman** [comment]
This issue will be addressed in the same way as [#180](https://github.com/keptn-contrib/dynatrace-service/issues/180) in the Dynatrace-Service
