### ISSUE TITLE
Enable/disable the feature of SLO/SLI generation from a DT-Dashboard

### ISSUE THREAD

**Issue by johannes-b** [keptn-contrib/dynatrace-sli-service#82]
**Status quo:**
When receiving a `sh.keptn.internal.event.get-sli.done` event, the dynatrace-sli-service always queries Dynatrace for all dashboards to determine whether there is one that for the service/project/stage to evaluate. This can become a time consuming and API heavy step for very large environments.

**Improvement:**
Introduce a flag as an environment variable that controls this behavior: 
`FETCH_SLO_SLI_FROM_DASHBOARD: [enabled | disabled | initial]`
  - `enabled`: Behavior as explained above. With each `sh.keptn.internal.event.get-sli.done` event, find the corresponding dashboard in Dynatrace.
  - `disabled`: No interaction with the dynatrace/dashboard API
  - `initial`: When the array of received SLI is empty, the dynatrace-service queries Dynatrace for the corresponding dashboard.

**Comment by grabnerandi** [comment]
I have some other ideas on this. 

If we want to go with the flag then lets introduce one that is enabling a cache: So - if the dynatrace sli service pulls the list of dashboards it can cache that list and doesnt refresh it for e.g: 1minute. this will eliminate multiple calls within a short period. Also - dashboards are not changed that frequent - so - 1 minute should be good

Another option is to push this into the dynatrace.conf.yaml file which contains confiugration items for both dynatrace and dnyatrace-sli service. That conf file already contains an option to specify a dashboard by ID. We could extend this and provide an option dashboard: query which would then query the list of dashboards. If that item is not specified it goes into the default mode which is not querying for dashboards.
This allows us to control the dashboard querying mechanism for each project, service and stage other than just have a global flag

**Comment by agrimmer** [comment]
At the moment, we did not experience performance issues when querying the dashboards yet. Therefore, I would like to postpone the idea with the cache.

However, I like the idea of making the query of the dashboard optional but without a `dynatrace.conf.yaml`. Therefore, let's introduce a feature flag as an environment variable (as we already do for the `dynatrace-service`).

Finally, I would not provide the option `initial` in the first version of this feature because requires to save the state, i.e. has the dashboards already be queried. We cannot do this in the pod as the pod can always be restarted.

**Comment by grabnerandi** [comment]
As discussed on slack this will be implemented using dynatrace.conf.yaml. There is a property called "dashboard" already. It will now be used with the following value options:
query: this will mean the sli-service will query the dynatrace dashboards and tries to find a name match KQG;project=project...
dashboard-uuid: if you pass in a dashboard uuid that dashboard will be queried
empty or no dynatrace.conf.yaml: will fall back to the original implementation by queriing the SLIs passed through the getSLI event
