### ISSUE TITLE
Allow keptn placeholders in dtCreds

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-sli-service#90]
This was brought up in a conversation with @leonvzGit - he had the requirement to also use placeholders, e.g: $PROJECT, $LABEL.ENV ... in dtCreds.

The use case is that they have different Dynatrace Tenants per Environment, e.g: dynatrace-prod, dynatrace-preprod.
The name of the Environment is always passed to Keptn via a Label, e.g: environment=prod, environment=preprod
They therefore define secrets that hold the DYnatrace Credentials called dynatrace-prod & dynatrace-preprod

In order to use the label and with that define which dynatrace tenant to be used he suggested to allow a dynatrace.conf.yaml like this
```
dtCreds: dynatrace-$LABEL.Environment
```

**Comment by agrimmer** [comment]
With this feature, a Keptn project-stage-service combination would not be mapped to one DT tenant. 
Can you please elaborate on the use case?

**Comment by grabnerandi** [comment]
I think I also commented on the PR Comment. Wanted to add here that this allows a user to use a standard dynatrace.conf.yaml across multiple projects and use metadata to make sure the correct credentials are used

**Comment by grabnerandi** [comment]
Here is my comment on the PR

I dont think it changes anything from before. Before you could define the secret name the dynatrace-sli-service should be using in dtCreds as a single string. Now we are simply allowing you to also use the the same placeholders we allow you to use in SLI definitions. It would allow you to map to different tenants - but - the same is true if you would simply change the values in the dynatrace-secret between quality gate runs.

**Comment by grabnerandi** [comment]
implemented in #89
